package com.proxy;

public class DEConstants {
	 /*		Begin++++DataEye相关+++++		*/
	  public static final String DETYPE = "type";							//DataEye type
	  public static final String DEACCOUNT = "accountId";					//DataEye accountId
	  public static final String DEACCOUNTYPE = "accountType";				//DataEye accountType
	  public static final String DESEX = "sex";								//DataEye sex
	  public static final String DEAGE = "age";								//DataEye age
	  public static final String DEGAMESERVER = "gameServer";				//DataEye gameServer
	  public static final String DELEVEL = "level";						//DataEye level
	  public static final String DENTAG = "nodeTag";						//DataEye nodeTag
	  public static final String DESTAG = "subTag";							//DataEye subTag
	  public static final String DELEVELID = "levelId";						//DataEye levelId
	  public static final String DEREASON = "reason";						//DataEye reason
	  public static final String DETASKID = "taskId";						//DataEye taskId
	  public static final String DEPLAYERTYPE = "playerType";				//DataEye playerType
	  public static final String DEITEMID = "itemId";						//DataEye itemId
	  public static final String DEITEMTYPE = "itemType";					//DataEye itemType
	  public static final String DEITEMCOUNT = "itemCount";					//DataEye itemCount
	  public static final String DEVITURALCURRENCY = "vituralCurrency";		//DataEye vituralCurrency
	  public static final String DECURRENCYTYPE = "currencyType";			//DataEye currencyType
	  public static final String DECONSUMEPOINT = "consumePoint";			//DataEye consumePoint
	  public static final String DECOINNUM = "coinNum";						//DataEye coinNum
	  public static final String DECOINTYPE = "coinType";					//DataEye coinType
	  public static final String DEGAIN = "gain";							//DataEye gain
	  public static final String DELEFT = "left";							//DataEye left
	  public static final String DELOST = "lost";							//DataEye lost
	  public static final String DEORDERID = "orderId";						//DataEye orderId
	  public static final String DEIAPID = "iapId";							//DataEye iapId
	  public static final String DECURRENCYAMOUNT = "currencyAmount";		//DataEye currencyAmount
	  public static final String DEPAYMENTTYPE = "paymentType";				//DataEye paymentType
	  public static final String DEEVENTID = "eventId";						//DataEye eventId
	  public static final String DELABEL = "label";							//DataEye label
	  public static final String DECOUNT = "count";							//DataEye count
	  public static final String DEDURATION = "duration";					//DataEye duration
	  public static final String DEFLAG = "flag";							//DataEye flag
	  public static final String DETITLE = "title";							//DataEye title
	  public static final String DEERROR = "error";							//DataEye error
	  public static final String DEKEY = "key";								//DataEye key
	  public static final String DEDEFAULTVALUE = "defaultValue";			//DataEye defaultValue
	  public static final String DEROOMID = "roomId";						//DataEye roomId
	  public static final String DEROOMTYPE = "roomType";					//DataEye roomType
	  public static final String DELOSEORGAIN = "loseOrGain";				//DataEye loseOrGain
	  public static final String DETAX = "tax";								//DataEye tax
	  public static final String DEVERSION = "version";						//DataEye version
	  public static final String DESECOND = "second";						//DataEye second
	  
	  public static final String DELOGIN =  "0" ;							//DataEye LOGIN
	  public static final String DELOGOUT = "1" ;							//DataEye LOGOUT
	  public static final String DEENTERGAME = "2" ;						//DataEye ENTERGAME
	  public static final String DELEVELCHANGE = "3" ;						//DataEye LEVELCHANGE
	  public static final String DEADDTAG = "4" ;							//DataEye ADDTAG
	  public static final String DEREMOVETAG = "5" ;						//DataEye REMOVETAG
	  public static final String DELEVELBEGIN = "6" ;						//DataEye LEVELBEGIN
	  public static final String DELEVELCOMPLETE = "7" ;					//DataEye LEVELCOMPLETE
	  public static final String DELEVELFAILD = "8" ;						//DataEye LEVELFAILD
	  public static final String DETASKBEGIN = "9" ;						//DataEye TASKBEGIN
	  public static final String DETASKCOMPLETE = "10" ;					//DataEye TASKCOMPLETE
	  public static final String DETASKFAILD = "11" ;						//DataEye TASKFAILD
	  public static final String DEPROPSBUY = "12" ;						//DataEye PROPSBUY
	  public static final String DEPROPSGET = "13" ;						//DataEye PROPSGET
	  public static final String DEPROPSCONSUME = "14" ;					//DataEye PROPSCONSUME
	  public static final String DESETCOINNUM = "15" ;						//DataEye SETCOINNUM
	  public static final String DEGAINCOIN = "16" ;						//DataEye GAINCOIN
	  public static final String DELOSTCOIN = "17" ;						//DataEye LOSTCOIN
	  public static final String DEPAYMENTSUCCESS = "18" ;					//DataEye PAYMENTSUCCESS
	  public static final String DEPAYMENTSUCCESSINLEVEL = "19" ;			//DataEye PAYMENTSUCCESSINLEVEL
	  public static final String DEBUYINLEVEL = "20" ;						//DataEye BUYINLEVEL
	  public static final String DEGETINLEVEL = "21" ;						//DataEye GETINLEVEL
	  public static final String DECONSUMEINLEVEL = "22" ;					//DataEye CONSUMEINLEVEL
	  public static final String DEGAININLEVEL = "23" ;						//DataEye GAININLEVEL
	  public static final String DELOSTINLEVEL = "24" ;						//DataEye LOSTINLEVEL
	  public static final String DEONEVENT = "25" ;							//DataEye ONEVENT
	  public static final String DEONEVENTSINGLE = "26" ;					//DataEye ONEVENTSINGLE
	  public static final String DEONEVENTMUTILE = "27" ;					//DataEye ONEVENTMUTILE
	  public static final String DEONEVENTCOUNT = "28" ;					//DataEye ONEVENTCOUNT
	  public static final String DEONEVENTDURATION = "29" ;					//DataEye ONEVENTDURATION
	  public static final String DEONEVENTDURATIONSINGLE = "30" ;			//DataEye ONEVENTDURATIONSINGLE
	  public static final String DEONEVENTDURATIONMUTILE = "31" ;			//DataEye ONEVENTDURATIONMUTILE
	  public static final String DEONEVENTBEGINSINGLE = "32" ;				//DataEye ONEVENTBEGINSINGLE
	  public static final String DEONEVENTBEGINMUTILE = "33" ;				//DataEye ONEVENTBEGINMUTILE
	  public static final String DEONEVENTENDSINGLE = "34" ;				//DataEye ONEVENTENDSINGLE
	  public static final String DEONEVENTENDMUTILE = "35" ;				//DataEye ONEVENTENDMUTILE
	  public static final String DEONEVENTBEFORELOGIN = "36" ;				//DataEye ONEVENTBEFORELOGIN
	  public static final String DEREPORTERRORSINGLE = "37" ;				//DataEye REPORTERRORSINGLE
	  public static final String DEREPORTERRORMUTILE = "38" ;				//DataEye REPORTERRORMUTILE
	  public static final String DEGETCONFIGPARAMSUPDATELISTENER = "39" ;	//DataEye GETCONFIGPARAMSUPDATELISTENER
	  public static final String DEUPDATE = "40" ;							//DataEye UPDATE
	  public static final String DEGETPARAMETERSTRING = "41" ;				//DataEye GETPARAMETERSTRING
	  public static final String DEGETPARAMETERINT = "42" ;					//DataEye GETPARAMETERINT
	  public static final String DEGETPARAMETERLONG = "43" ;				//DataEye GETPARAMETERLONG
	  public static final String DEGETPARAMETERBOOL = "44" ;				//DataEye GETPARAMETERBOOL
	  public static final String DECHESSPLAY = "45" ;						//DataEye CHESSPLAY
	  public static final String DECHESSLOST = "46" ;						//DataEye CHESSLOST
	  public static final String DECHESSGAIN = "47" ;						//DataEye CHESSGAIN
	  public static final String DESETVERSION = "48" ;						//DataEye SETVERSION
	  public static final String DESETUPLOADINTERVAL = "49" ;				//DataEye SETUPLOADINTERVAL
	  public static final String DEUPLOADNOW = "50" ;						//DataEye UPLOADNOW
	  public static final String DEGETUID = "51" ;							//DataEye GETUID
	  public static final String DEONEVENTBEGINMUTILEFLAG = "52" ;			//DataEye ONEVENTBEGINMUTILEFLAG
	  /*		End++++DataEye相关+++++		*/
}
